### ISSUE TITLE
Produce basemaps release in sync with MapServer releases

### ISSUE THREAD

**Issue by dmorissette** [mapserver/basemaps#18]
At the moment we do not produce formal releases of basemaps, so basemaps is always a moving target and users of stable MapServer releases (e.g. 6.2) end up getting errors when they try to use the master basemaps from github which contains some changes requiring the master dev version of MapServer.

Ideally the basemaps package should be branched in github and released at the same time as the source code, this way users could have basemaps versions corresponding to their mapserver version.

i.e. When we release "MapServer 6.2" we would also release "Basemaps for MapServer 6.2".

**Comment by sgrossberndt** [comment]
Can be closed.
