### ISSUE TITLE
osm_new_landusages_gen00 does not exists

### ISSUE THREAD

**Issue by kinju** [MapServer/basemaps#23]
In the generated mapfiles, there is two layers (landuse4 and landuse5) which takes data from "osm_new_landusages_gen00". But osm_new_landusages_gen00 does not exists.

I replaced them by "osm_new_landusages_gen0" and it works.

**Comment by MinChanSike** [comment]
**imposm** is not support for windows platform.
So, how can I solve that osm_new_landusages_gen00 does not exists issue?

**Comment by yjacolin** [comment]
you can probably use docker on windows: https://github.com/kartoza/docker-osm

**Comment by yjacolin** [comment]
Are you sure imposm doesn't work on Windows?

**Comment by MinChanSike** [comment]
Yes, as my googling there is no imposm for Windows.  :'(
