### ISSUE TITLE
How  to enable generation of buildings

### ISSUE THREAD

**Issue by kytay** [mapserver/basemaps#30]
Hi I have tried to add buildings.map in the line "include=" in the Makefile. But I cannot get the basemap to generate the buildings layer. Am I missing out some other configurations?

**Comment by sgrossberndt** [comment]
Can be closed.

**Comment by yjacolin** [comment]
@sgrossberndt can't you close ticket? I don't think it is limited to admin or commiter. Am I wrong?

**Comment by sgrossberndt** [comment]
My current rights on the repository do not allow to do so.
