### ISSUE TITLE
Urgent - Generation of basemap for osm2pgsql fails

### ISSUE THREAD

**Issue by bivatury** [mapserver/basemaps#34]
Hello Ive imported OSM data for northamerica. Following are the tables that are generated. 
 List of relations
 Schema |         Name         |   Type   |  Owner
--------+----------------------+----------+----------
 public | geography_columns    | view     | postgres
 public | geometry_columns     | view     | postgres
 public | planet_osm_line      | table    | osmuser
 public | planet_osm_nodes     | table    | osmuser
 public | planet_osm_point     | table    | osmuser
 public | planet_osm_polygon   | table    | osmuser
 public | planet_osm_rels      | table    | osmuser
 public | planet_osm_roads     | table    | osmuser
 public | planet_osm_ways      | table    | osmuser
 public | raster_columns       | view     | postgres
 public | raster_overviews     | view     | postgres
 public | spatial_ref_sys      | table    | postgres
 public | tbt_tmp_rings        | table    | osmuser
 public | tbt_tmp_rings_id_seq | sequence | osmuser

When I run the basemap pre-requisite utility im getting whole bunch of errors . Why is it so. 

There is no right document pointing to right basemaps for osm2pgsql generator. 

Here is the errors 

psql:osm2pgsql-to-imposm-schema.sql:840: ERROR:  relation "osm_new_mainroads_gen0_view" does not exist
LINE 4:   FROM osm_new_mainroads_gen0_view
               ^
psql:osm2pgsql-to-imposm-schema.sql:842: ERROR:  "osm_new_roads_gen0" is not a table
HINT:  Use DROP VIEW to remove a view.
psql:osm2pgsql-to-imposm-schema.sql:845: ERROR:  relation "osm_new_roads_gen0_view" does not exist
LINE 2:   SELECT \* FROM osm_new_roads_gen0_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:847: ERROR:  "osm_new_roads_gen0" is not a table
psql:osm2pgsql-to-imposm-schema.sql:850: ERROR:  "osm_new_roads_gen0" is not a table, composite type, or foreign table
psql:osm2pgsql-to-imposm-schema.sql:855: ERROR:  cannot update view "osm_new_roads_gen0"
DETAIL:  Views containing UNION, INTERSECT, or EXCEPT are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
psql:osm2pgsql-to-imposm-schema.sql:859: ERROR:  cannot update view "osm_new_roads_gen0"
DETAIL:  Views containing UNION, INTERSECT, or EXCEPT are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
psql:osm2pgsql-to-imposm-schema.sql:867: ERROR:  cannot update view "osm_new_roads_gen0"
DETAIL:  Views containing UNION, INTERSECT, or EXCEPT are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
psql:osm2pgsql-to-imposm-schema.sql:870: ERROR:  "osm_new_roads_gen0" is not a table or materialized view
psql:osm2pgsql-to-imposm-schema.sql:871: ERROR:  "osm_new_roads_gen0" is not a table or materialized view
psql:osm2pgsql-to-imposm-schema.sql:873: ERROR:  "osm_new_roads_gen0" is not a table
psql:osm2pgsql-to-imposm-schema.sql:874: ERROR:  "osm_new_roads_gen0" is not a table
psql:osm2pgsql-to-imposm-schema.sql:875: ERROR:  "osm_new_roads_gen0" is not a table
psql:osm2pgsql-to-imposm-schema.sql:883: NOTICE:  view "osm_new_roads_gen1_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:895: ERROR:  relation "osm_new_mainroads_gen1_view" does not exist
LINE 4:   FROM osm_new_mainroads_gen1_view
               ^
psql:osm2pgsql-to-imposm-schema.sql:897: ERROR:  "osm_new_roads_gen1" is not a table
HINT:  Use DROP VIEW to remove a view.
psql:osm2pgsql-to-imposm-schema.sql:900: ERROR:  relation "osm_new_roads_gen1_view" does not exist
LINE 2:   SELECT \* FROM osm_new_roads_gen1_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:902: ERROR:  "osm_new_roads_gen1" is not a table
psql:osm2pgsql-to-imposm-schema.sql:905: ERROR:  "osm_new_roads_gen1" is not a table, composite type, or foreign table
psql:osm2pgsql-to-imposm-schema.sql:910: ERROR:  cannot update view "osm_new_roads_gen1"
DETAIL:  Views containing UNION, INTERSECT, or EXCEPT are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
psql:osm2pgsql-to-imposm-schema.sql:914: ERROR:  cannot update view "osm_new_roads_gen1"
DETAIL:  Views containing UNION, INTERSECT, or EXCEPT are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
psql:osm2pgsql-to-imposm-schema.sql:922: ERROR:  cannot update view "osm_new_roads_gen1"
DETAIL:  Views containing UNION, INTERSECT, or EXCEPT are not automatically updatable.
HINT:  To enable updating the view, provide an INSTEAD OF UPDATE trigger or an unconditional ON UPDATE DO INSTEAD rule.
psql:osm2pgsql-to-imposm-schema.sql:925: ERROR:  "osm_new_roads_gen1" is not a table or materialized view
psql:osm2pgsql-to-imposm-schema.sql:926: ERROR:  "osm_new_roads_gen1" is not a table or materialized view
psql:osm2pgsql-to-imposm-schema.sql:928: ERROR:  "osm_new_roads_gen1" is not a table
psql:osm2pgsql-to-imposm-schema.sql:929: ERROR:  "osm_new_roads_gen1" is not a table
psql:osm2pgsql-to-imposm-schema.sql:930: ERROR:  "osm_new_roads_gen1" is not a table
psql:osm2pgsql-to-imposm-schema.sql:938: NOTICE:  view "osm_new_transport_areas_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:948: ERROR:  relation "osm_polygon" does not exist
LINE 4:   FROM osm_polygon
               ^
psql:osm2pgsql-to-imposm-schema.sql:950: NOTICE:  table "osm_new_transport_areas" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:953: ERROR:  relation "osm_new_transport_areas_view" does not exist
LINE 2:   SELECT \* FROM osm_new_transport_areas_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:955: ERROR:  relation "osm_new_transport_areas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:958: ERROR:  relation "osm_new_transport_areas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:959: ERROR:  relation "osm_new_transport_areas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:961: ERROR:  relation "osm_new_transport_areas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:962: ERROR:  relation "osm_new_transport_areas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:970: NOTICE:  view "osm_new_transport_points_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:998: ERROR:  relation "osm_point" does not exist
LINE 4:   FROM osm_point
               ^
psql:osm2pgsql-to-imposm-schema.sql:1000: NOTICE:  table "osm_new_transport_points" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1003: ERROR:  relation "osm_new_transport_points_view" does not exist
LINE 2:   SELECT \* FROM osm_new_transport_points_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1005: ERROR:  relation "osm_new_transport_points" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1008: ERROR:  relation "osm_new_transport_points" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1009: ERROR:  relation "osm_new_transport_points" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1011: ERROR:  relation "osm_new_transport_points" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1012: ERROR:  relation "osm_new_transport_points" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1013: ERROR:  relation "osm_new_transport_points" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1020: NOTICE:  view "osm_new_waterareas_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:1034: ERROR:  relation "osm_polygon" does not exist
LINE 4:   FROM osm_polygon
               ^
psql:osm2pgsql-to-imposm-schema.sql:1036: NOTICE:  table "osm_new_waterareas" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1039: ERROR:  relation "osm_new_waterareas_view" does not exist
LINE 2:   SELECT \* FROM osm_new_waterareas_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1041: ERROR:  relation "osm_new_waterareas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1044: ERROR:  relation "osm_new_waterareas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1045: ERROR:  relation "osm_new_waterareas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1047: ERROR:  relation "osm_new_waterareas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1048: ERROR:  relation "osm_new_waterareas" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1056: NOTICE:  view "osm_new_waterareas_gen0_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:1060: ERROR:  relation "osm_new_waterareas_view" does not exist
LINE 3:   FROM osm_new_waterareas_view where ST_Area(geometry)>50000...
               ^
psql:osm2pgsql-to-imposm-schema.sql:1062: NOTICE:  table "osm_new_waterareas_gen0" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1065: ERROR:  relation "osm_new_waterareas_gen0_view" does not exist
LINE 2:   SELECT \* FROM osm_new_waterareas_gen0_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1067: ERROR:  relation "osm_new_waterareas_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1070: ERROR:  relation "osm_new_waterareas_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1071: ERROR:  relation "osm_new_waterareas_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1073: ERROR:  relation "osm_new_waterareas_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1074: ERROR:  relation "osm_new_waterareas_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1081: NOTICE:  view "osm_new_waterareas_gen1_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:1085: ERROR:  relation "osm_new_waterareas_view" does not exist
LINE 3:   FROM osm_new_waterareas_view where ST_Area(geometry)>50000...
               ^
psql:osm2pgsql-to-imposm-schema.sql:1087: NOTICE:  table "osm_new_waterareas_gen1" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1090: ERROR:  relation "osm_new_waterareas_gen1_view" does not exist
LINE 2:   SELECT \* FROM osm_new_waterareas_gen1_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1092: ERROR:  relation "osm_new_waterareas_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1095: ERROR:  relation "osm_new_waterareas_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1096: ERROR:  relation "osm_new_waterareas_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1098: ERROR:  relation "osm_new_waterareas_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1099: ERROR:  relation "osm_new_waterareas_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1107: NOTICE:  view "osm_new_waterways_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:1116: ERROR:  relation "osm_line" does not exist
LINE 3:   FROM osm_line
               ^
psql:osm2pgsql-to-imposm-schema.sql:1118: NOTICE:  table "osm_new_waterways" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1121: ERROR:  relation "osm_new_waterways_view" does not exist
LINE 2:   SELECT \* FROM osm_new_waterways_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1123: ERROR:  relation "osm_new_waterways" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1126: ERROR:  relation "osm_new_waterways" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1127: ERROR:  relation "osm_new_waterways" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1129: ERROR:  relation "osm_new_waterways" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1130: ERROR:  relation "osm_new_waterways" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1131: ERROR:  relation "osm_new_waterways" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1139: NOTICE:  view "osm_new_waterways_gen0_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:1143: ERROR:  relation "osm_new_waterways_view" does not exist
LINE 3:   FROM osm_new_waterways_view;
               ^
psql:osm2pgsql-to-imposm-schema.sql:1145: NOTICE:  table "osm_new_waterways_gen0" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1148: ERROR:  relation "osm_new_waterways_gen0_view" does not exist
LINE 2:   SELECT \* FROM osm_new_waterways_gen0_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1150: ERROR:  relation "osm_new_waterways_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1153: ERROR:  relation "osm_new_waterways_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1154: ERROR:  relation "osm_new_waterways_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1156: ERROR:  relation "osm_new_waterways_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1157: ERROR:  relation "osm_new_waterways_gen0" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1164: NOTICE:  view "osm_new_waterways_gen1_view" does not exist, skipping
DROP VIEW
psql:osm2pgsql-to-imposm-schema.sql:1168: ERROR:  relation "osm_new_waterways_view" does not exist
LINE 3:   FROM osm_new_waterways_view;
               ^
psql:osm2pgsql-to-imposm-schema.sql:1170: NOTICE:  table "osm_new_waterways_gen1" does not exist, skipping
DROP TABLE
psql:osm2pgsql-to-imposm-schema.sql:1173: ERROR:  relation "osm_new_waterways_gen1_view" does not exist
LINE 2:   SELECT \* FROM osm_new_waterways_gen1_view;
                        ^
psql:osm2pgsql-to-imposm-schema.sql:1175: ERROR:  relation "osm_new_waterways_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1178: ERROR:  relation "osm_new_waterways_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1179: ERROR:  relation "osm_new_waterways_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1181: ERROR:  relation "osm_new_waterways_gen1" does not exist
psql:osm2pgsql-to-imposm-schema.sql:1182: ERROR:  relation "osm_new_waterways_gen1" does not exist

Im having an urgent request from one of my client to set this up for an critical business requrement any help urgently is appreciate. If im doing some thing wrong please point me to right URL. 

Thanks and regards 
Bhushan

**Comment by yjacolin** [comment]
Could you write the command line and all the log. I am a little bit suprise that the problem starts to line 840 as the view osm_new_mainroads_gen0_view is created there: https://github.com/mapserver/basemaps/blob/master/contrib/osm2pgsql-to-imposm-schema.sql#L417

**Comment by bivatury** [comment]
Hello This is the command used 
sudo -h MY_DB_HOST -u postgres  psql -U postgres -d MY_DB_NAME -f "osm2pgsql-to-imposm-schema.sql"

**Comment by bivatury** [comment]
Attaching the log file 
[log.txt](https://github.com/mapserver/basemaps/files/568564/log.txt)

**Comment by yjacolin** [comment]
Thanks, the problem come from the prefix used in your table: **planet_**osm_polygon instead of osm_planet as it is in the sql file.

So could you rename your planet_osm_polygon into osm_polygon (same for roads, line and point) or start again a data import? You have an option to use with osm2pgsql to remove the table prefix.
```
$ osm2pgsql --help
[..]
-p|--prefix          Prefix for table names (default planet_osm) 
[..]
```

**Comment by bivatury** [comment]
Oh Ok . Didint realize that could be the problem. Shall do check as the import take a while 7Gig.

**Comment by yjacolin** [comment]
imposm is really much faster ;) and imposm v3 is really much much faster :) but it depends if other applications depends on of your current table name or not.

**Comment by yjacolin** [comment]
Please, could you confirm that it is the solution as I have a PR waiting to be merge :)

**Comment by bivatury** [comment]
i agree imposm is faster but the need is to use osm2pgsql. Thanks for pointing out .

**Comment by bivatury** [comment]
Shall confirm with a small db import

**Comment by bivatury** [comment]
It worked - thank you .
