### ISSUE TITLE
Getting openstreetmap layers to work.

### ISSUE THREAD

**Issue by atlantageek** [mapserver/basemaps#55]
What does this mean from the wiki

Get the following layer simplified_land_polygon http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip in basemaps/data/

am i suppose to unzip the file in the basemaps/data layer?

**Comment by yjacolin** [comment]
yes you should unzip the file.

Please could you use mailing list for such question :) Thanks.
