### ISSUE TITLE
Missing Style Definition for Layer MapServer 6.0

### ISSUE THREAD

**Issue by jlarouche** [mapserver/basemaps#9]
Hello,

There is a problem with the places.map CLASS definition when using Basemaps with Mapserver 6.0. There's no STYLE in the CLASS and so Mapserver returns the "msAddLabel error: missing style definition for layer".

This problem doesn't seem to be present when using MapServer 6.2.
The easy fix is (instead of linking a big patch that adds almost nothing :p)

```
mv places.map places.map.old
sed '/\bCLASS\b/ a\
STYLE END' places.map.old > places.map
rm places.map.old
```

It only adds STYLE END after each CLASS statement.

```
CLASS
STYLE END
....
END
```

I don't know if you want to keep support for MapServer 6.0 and I don't know if this fix would break with MapServer 6.2.

**Comment by sgrossberndt** [comment]
Can be closed.
